server:
  port: 6677

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  resources:
    static-locations: classpath:/
  datasource:
    url: jdbc:mysql://192.168.2.198:3306/mdm?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: zhang@123
    driver-class-name: com.mysql.cj.jdbc.Driver